from typing import Any
from PySide6.QtWidgets import QWidget
from collections.abc import Hashable

class Globals:
    def globals(self, name: Hashable, value: Any) -> None: ...
    def getGlobals(self, name: Hashable) -> Any: ...
    def delGlobals(self, name: Hashable) -> None: ...

class Default:
    def string(self, value: Any) -> Any: ...
    def onClicked(self, scope: str, widget: QWidget, value: Any = None) -> None: ...
    def call_block(self, scope: list | str, accept: Any = None) -> None: ...
    def hook(self, name: str, value: Any) -> None: ...
    def exec_code(self, code: dict, *args, **kw) -> None: ...
    def get_all_hooks(self, code: dict) -> list: ...

class Log:
    @staticmethod
    def debug_print(msg: Any) -> None:  ...
    @staticmethod
    def info_print(msg: Any) -> None: ...
    @staticmethod
    def error_print(msg: Any, _type: str) -> None: ...
